using System;
using System.Collections.Generic;
#if ODIN_INSPECTOR
using Sirenix.OdinInspector;
#endif

namespace Cadence
{
    /// <summary>
    /// A proposal to adjust difficulty parameters, generated by the Adjustment Engine.
    /// Contains one or more <see cref="ParameterDelta"/> entries from different rules.
    /// </summary>
    [Serializable]
    public class AdjustmentProposal
    {
#if ODIN_INSPECTOR
        [PropertyTooltip("List of parameter changes proposed by the adjustment rules.\n" +
                          "Each delta specifies the parameter key, current value, proposed value, and which rule generated it.")]
        [ListDrawerSettings(ShowFoldout = true, DraggableItems = false)]
#endif
        public List<ParameterDelta> Deltas = new List<ParameterDelta>();

#if ODIN_INSPECTOR
        [PropertyTooltip("Confidence in this proposal, pulled from PlayerSkillProfile.Confidence01.\n" +
                          "Higher confidence = more reliable prediction.")]
        [ProgressBar(0f, 1f)]
#endif
        public float Confidence;

#if ODIN_INSPECTOR
        [PropertyTooltip("Human-readable explanation of why this proposal was generated.\n" +
                          "Includes flow state, streak info, and frustration scores.")]
#endif
        public string Reason;

#if ODIN_INSPECTOR
        [PropertyTooltip("The flow state that triggered or informed this proposal.")]
#endif
        public FlowState DetectedState;

#if ODIN_INSPECTOR
        [PropertyTooltip("When to apply this proposal:\n" +
                          "BeforeNextLevel = apply before loading the next level (normal).\n" +
                          "MidSession = apply immediately (frustration relief).")]
#endif
        public AdjustmentTiming Timing;
    }

    /// <summary>
    /// When the adjustment should be applied.
    /// </summary>
    public enum AdjustmentTiming : byte
    {
        /// <summary>Apply before the next level starts (standard between-session adjustment).</summary>
        BeforeNextLevel = 0,

        /// <summary>Apply immediately during the current session (emergency frustration relief).</summary>
        MidSession = 1
    }
}
