using System;
using System.Collections.Generic;
#if ODIN_INSPECTOR
using Sirenix.OdinInspector;
#endif

namespace Cadence
{
    /// <summary>
    /// A proposal to adjust difficulty parameters, generated by the Adjustment Engine.
    /// Contains one or more <see cref="ParameterDelta"/> entries from different rules.
    /// </summary>
    [Serializable]
    public class AdjustmentProposal
    {
        public const float DefaultLowConfidenceStepCapThreshold = 0.4f;
        public const int DefaultLowConfidenceMaxAbsVariantStep = 1;

#if ODIN_INSPECTOR
        [PropertyTooltip("List of parameter changes proposed by the adjustment rules.\n" +
                          "Each delta specifies the parameter key, current value, proposed value, and which rule generated it.")]
        [ListDrawerSettings(ShowFoldout = true, DraggableItems = false)]
#endif
        public List<ParameterDelta> Deltas = new List<ParameterDelta>();

#if ODIN_INSPECTOR
        [PropertyTooltip("Confidence in this proposal, pulled from PlayerSkillProfile.Confidence01.\n" +
                          "Higher confidence = more reliable prediction.")]
        [ProgressBar(0f, 1f)]
#endif
        public float Confidence;

#if ODIN_INSPECTOR
        [PropertyTooltip("Stable normalized attribution for the rule that drove this proposal.")]
#endif
        public string RuleFired = AdjustmentRuleAttribution.None;

#if ODIN_INSPECTOR
        [PropertyTooltip("Human-readable explanation of why this proposal was generated.\n" +
                          "Includes flow state, streak info, and frustration scores.")]
#endif
        public string Reason;

#if ODIN_INSPECTOR
        [PropertyTooltip("The flow state that triggered or informed this proposal.")]
#endif
        public FlowState DetectedState;

#if ODIN_INSPECTOR
        [PropertyTooltip("When to apply this proposal:\n" +
                          "BeforeNextLevel = apply before loading the next level (normal).\n" +
                          "MidSession = apply immediately (frustration relief).")]
#endif
        public AdjustmentTiming Timing;

        /// <summary>
        /// Applies the SDK's low-confidence variant-step cap to a host-game variant step.
        /// Use this at the final mapping point where a generic proposal is converted into a variant delta.
        /// </summary>
        public int CapVariantStepForConfidence(int proposalStep)
        {
            return CapVariantStepForConfidence(proposalStep, Confidence);
        }

        /// <summary>
        /// Caps variant steps to a small magnitude while the player profile is still low confidence.
        /// This keeps noisy early-session data from causing large difficulty jumps.
        /// </summary>
        public static int CapVariantStepForConfidence(int proposalStep, float confidence,
            float confidenceThreshold = DefaultLowConfidenceStepCapThreshold,
            int maxAbsStep = DefaultLowConfidenceMaxAbsVariantStep)
        {
            if (!float.IsNaN(confidence) && confidence >= confidenceThreshold)
                return proposalStep;

            int absCap = Math.Max(0, maxAbsStep);
            return Math.Max(-absCap, Math.Min(absCap, proposalStep));
        }

        /// <summary>
        /// Prevents a same-level retry after a failed attempt from increasing difficulty.
        /// Use this after the host converts a proposal into a variant step.
        /// </summary>
        public static int CapVariantStepForFailedRetry(int proposalStep, bool isFailedRetry)
        {
            return isFailedRetry ? Math.Min(0, proposalStep) : proposalStep;
        }

        /// <summary>
        /// Prevents a same-level retry after a failed attempt from serving a harder variant
        /// than the variant that was just failed.
        /// </summary>
        public static int CapVariantForFailedRetry(int proposedVariant, int failedVariant,
            bool isFailedRetry)
        {
            return isFailedRetry ? Math.Min(proposedVariant, failedVariant) : proposedVariant;
        }
    }

    /// <summary>
    /// When the adjustment should be applied.
    /// </summary>
    public enum AdjustmentTiming : byte
    {
        /// <summary>Apply before the next level starts (standard between-session adjustment).</summary>
        BeforeNextLevel = 0,

        /// <summary>Apply immediately during the current session (emergency frustration relief).</summary>
        MidSession = 1
    }

    /// <summary>
    /// Stable analytics attribution names for proposal decisions.
    /// </summary>
    public static class AdjustmentRuleAttribution
    {
        public const string FlowChannel = "flow_channel";
        public const string StreakDamper = "streak_damper";
        public const string FrustrationRelief = "frustration_relief";
        public const string NewPlayer = "new_player";
        public const string SessionFatigue = "session_fatigue";
        public const string CooldownBlocked = "cooldown_blocked";
        public const string GateBlocked = "gate_blocked";
        public const string None = "none";

        public static string Normalize(string ruleName)
        {
            switch (ruleName)
            {
                case "FlowChannel":
                case FlowChannel:
                    return FlowChannel;
                case "StreakDamper":
                case StreakDamper:
                    return StreakDamper;
                case "FrustrationRelief":
                case FrustrationRelief:
                    return FrustrationRelief;
                case "NewPlayer":
                case NewPlayer:
                    return NewPlayer;
                case "SessionFatigue":
                case SessionFatigue:
                    return SessionFatigue;
                case "Cooldown":
                case CooldownBlocked:
                    return CooldownBlocked;
                case "GateBlocked":
                case GateBlocked:
                    return GateBlocked;
                default:
                    return None;
            }
        }
    }
}
