using System;
using UnityEngine;
#if ODIN_INSPECTOR
using Sirenix.OdinInspector;
#endif

namespace Cadence
{
    /// <summary>
    /// A single proposed change to a level parameter.
    /// Generated by adjustment rules, clamped by MaxDeltaPerAdjustment, scaled by sawtooth multiplier.
    /// </summary>
    [Serializable]
    public struct ParameterDelta
    {
#if ODIN_INSPECTOR
        [PropertyTooltip("The level parameter being adjusted (e.g., \"move_limit\", \"time_limit\", \"goal_count\").\n" +
                          "Must match a key in the level parameters dictionary passed to GetProposal().")]
#endif
        public string ParameterKey;

#if ODIN_INSPECTOR
        [PropertyTooltip("The parameter's current value before adjustment.")]
#endif
        public float CurrentValue;

#if ODIN_INSPECTOR
        [PropertyTooltip("The proposed new value after adjustment.\n" +
                          "Clamped to within MaxDeltaPerAdjustment (default 15%) of CurrentValue.")]
#endif
        public float ProposedValue;

#if ODIN_INSPECTOR
        [PropertyTooltip("Which adjustment rule generated this delta.\n" +
                          "Possible values: \"FlowChannel\", \"StreakDamper\", \"FrustrationRelief\".")]
#endif
        public string RuleName;

        /// <summary>The actual change: ProposedValue - CurrentValue. Negative = easier, Positive = harder.</summary>
        public float Delta => ProposedValue - CurrentValue;
    }
}
