using System;
using System.Collections.Generic;
#if ODIN_INSPECTOR
using Sirenix.OdinInspector;
#endif

namespace Cadence
{
    /// <summary>
    /// Complete snapshot of the DDA system state for the Debug Window and Sandbox Dashboard.
    /// Returned by <see cref="IDDAService.GetDebugSnapshot"/>.
    /// </summary>
    [Serializable]
    public class DDADebugData
    {
#if ODIN_INSPECTOR
        [BoxGroup("Session")]
        [PropertyTooltip("Whether a session is currently active (between BeginSession and EndSession).")]
#endif
        public bool SessionActive;

#if ODIN_INSPECTOR
        [BoxGroup("Session")]
        [PropertyTooltip("The level ID passed to BeginSession.")]
#endif
        public string CurrentLevelId;

#if ODIN_INSPECTOR
        [BoxGroup("Session")]
        [PropertyTooltip("The level type for the current session.")]
#endif
        public LevelType CurrentLevelType;

#if ODIN_INSPECTOR
        [BoxGroup("Session")]
        [SuffixLabel("sec", Overlay = true)]
#endif
        public float SessionTime;

#if ODIN_INSPECTOR
        [BoxGroup("Session")]
#endif
        public int TotalSignals;

#if ODIN_INSPECTOR
        [BoxGroup("Session")]
#endif
        public int RingBufferCount;

#if ODIN_INSPECTOR
        [BoxGroup("Session")]
        [PropertyTooltip("Completed levels in the current contiguous play session.")]
#endif
        public int LevelsThisSession;

#if ODIN_INSPECTOR
        [BoxGroup("Session")]
        [PropertyTooltip("True when the completed-level count is past the fatigue threshold and the next proposal may get session-fatigue easing.")]
#endif
        public bool SessionFatigueActive;

#if ODIN_INSPECTOR
        [BoxGroup("Session")]
        [PropertyTooltip("True when meta.abandoned has been recorded during the active session and EndSession() will coerce to Abandoned.")]
#endif
        public bool ExplicitAbandonPending;

#if ODIN_INSPECTOR
        [BoxGroup("Session")]
        [PropertyTooltip("Par moves for the current level (from level parameters).")]
#endif
        public float ParMoves;

#if ODIN_INSPECTOR
        [BoxGroup("Session")]
        [PropertyTooltip("Skill index from the last session summary.")]
#endif
        public float SkillIndex;

#if ODIN_INSPECTOR
        [BoxGroup("Session")]
        [PropertyTooltip("True when the last session was a replay (play_type == 2).")]
#endif
        public bool IsReplaySession;

#if ODIN_INSPECTOR
        [BoxGroup("Flow Detection")]
        [PropertyTooltip("Current real-time flow state reading.")]
#endif
        public FlowReading CurrentFlow;

#if ODIN_INSPECTOR
        [BoxGroup("Player Model")]
        [PropertyTooltip("Current player skill profile (Glicko-2 rating, history, stats).")]
#endif
        public PlayerSkillProfile Profile;

#if ODIN_INSPECTOR
        [BoxGroup("Player Model")]
        [PropertyTooltip("Current player archetype classification.")]
#endif
        public PlayerArchetypeReading ArchetypeReading;

#if ODIN_INSPECTOR
        [BoxGroup("Session Analysis")]
        [PropertyTooltip("Summary of the last completed session (aggregated signals and derived scores).")]
#endif
        public SessionSummary LastSessionSummary;

#if ODIN_INSPECTOR
        [BoxGroup("Adjustment")]
        [PropertyTooltip("The most recent adjustment proposal generated by the engine.")]
#endif
        public AdjustmentProposal LastProposal;

#if ODIN_INSPECTOR
        [BoxGroup("Adjustment")]
        [PropertyTooltip("Current level parameters that proposals are generated against.")]
#endif
        public Dictionary<string, float> CurrentLevelParams;
    }
}
